Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import seaborn as sns
from pandas import DataFrame as df

nclusters = range(2, 11)  # graspologic nclusters goes from 2 to max_clusters
bic = gm_clust.bic_  # obtain the respective silhouette scores

bic_df = df({"Number of Clusters": nclusters, "BIC": bic})  # place into pandas dataframe

fig, ax = plt.subplots(1,1,figsize=(12, 6))

sns.lineplot(data=silhouette_df,ax=ax, x="Number of Clusters", y="Silhouette Score");
ax.set_title("Silhouette Analysis of KMeans Clusterings")
fig;
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [24][0m, in [0;36m<module>[0;34m[0m
[1;32m      4[0m nclusters [38;5;241m=[39m [38;5;28mrange[39m([38;5;241m2[39m, [38;5;241m11[39m)  [38;5;66;03m# graspologic nclusters goes from 2 to max_clusters[39;00m
[1;32m      5[0m bic [38;5;241m=[39m gm_clust[38;5;241m.[39mbic_  [38;5;66;03m# obtain the respective silhouette scores[39;00m
[0;32m----> 7[0m bic_df [38;5;241m=[39m [43mdf[49m[43m([49m[43m{[49m[38;5;124;43m"[39;49m[38;5;124;43mNumber of Clusters[39;49m[38;5;124;43m"[39;49m[43m:[49m[43m [49m[43mnclusters[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mBIC[39;49m[38;5;124;43m"[39;49m[43m:[49m[43m [49m[43mbic[49m[43m}[49m[43m)[49m  [38;5;66;03m# place into pandas dataframe[39;00m
[1;32m      9[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m,[38;5;241m1[39m,figsize[38;5;241m=[39m([38;5;241m12[39m, [38;5;241m6[39m))
[1;32m     11[0m sns[38;5;241m.[39mlineplot(data[38;5;241m=[39msilhouette_df,ax[38;5;241m=[39max, x[38;5;241m=[39m[38;5;124m"[39m[38;5;124mNumber of Clusters[39m[38;5;124m"[39m, y[38;5;241m=[39m[38;5;124m"[39m[38;5;124mSilhouette Score[39m[38;5;124m"[39m);

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/frame.py:614[0m, in [0;36mDataFrame.__init__[0;34m(self, data, index, columns, dtype, copy)[0m
[1;32m    608[0m     mgr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_init_mgr(
[1;32m    609[0m         data, axes[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mindex[39m[38;5;124m"[39m: index, [38;5;124m"[39m[38;5;124mcolumns[39m[38;5;124m"[39m: columns}, dtype[38;5;241m=[39mdtype, copy[38;5;241m=[39mcopy
[1;32m    610[0m     )
[1;32m    612[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(data, [38;5;28mdict[39m):
[1;32m    613[0m     [38;5;66;03m# GH#38939 de facto copy defaults to False only in non-dict cases[39;00m
[0;32m--> 614[0m     mgr [38;5;241m=[39m [43mdict_to_mgr[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mindex[49m[43m,[49m[43m [49m[43mcolumns[49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m,[49m[43m [49m[43mtyp[49m[38;5;241;43m=[39;49m[43mmanager[49m[43m)[49m
[1;32m    615[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(data, ma[38;5;241m.[39mMaskedArray):
[1;32m    616[0m     [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mma[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmrecords[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmrecords[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/internals/construction.py:464[0m, in [0;36mdict_to_mgr[0;34m(data, index, columns, dtype, typ, copy)[0m
[1;32m    456[0m     arrays [38;5;241m=[39m [
[1;32m    457[0m         x
[1;32m    458[0m         [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(x, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m) [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(x[38;5;241m.[39mdtype, ExtensionDtype)
[1;32m    459[0m         [38;5;28;01melse[39;00m x[38;5;241m.[39mcopy()
[1;32m    460[0m         [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m arrays
[1;32m    461[0m     ]
[1;32m    462[0m     [38;5;66;03m# TODO: can we get rid of the dt64tz special case above?[39;00m
[0;32m--> 464[0m [38;5;28;01mreturn[39;00m [43marrays_to_mgr[49m[43m([49m
[1;32m    465[0m [43m    [49m[43marrays[49m[43m,[49m[43m [49m[43mdata_names[49m[43m,[49m[43m [49m[43mindex[49m[43m,[49m[43m [49m[43mcolumns[49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m,[49m[43m [49m[43mtyp[49m[38;5;241;43m=[39;49m[43mtyp[49m[43m,[49m[43m [49m[43mconsolidate[49m[38;5;241;43m=[39;49m[43mcopy[49m
[1;32m    466[0m [43m[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/internals/construction.py:124[0m, in [0;36marrays_to_mgr[0;34m(arrays, arr_names, index, columns, dtype, verify_integrity, typ, consolidate)[0m
[1;32m    121[0m         index [38;5;241m=[39m ensure_index(index)
[1;32m    123[0m     [38;5;66;03m# don't force copy because getting jammed in an ndarray anyway[39;00m
[0;32m--> 124[0m     arrays [38;5;241m=[39m [43m_homogenize[49m[43m([49m[43marrays[49m[43m,[49m[43m [49m[43mindex[49m[43m,[49m[43m [49m[43mdtype[49m[43m)[49m
[1;32m    126[0m [38;5;28;01melse[39;00m:
[1;32m    127[0m     index [38;5;241m=[39m ensure_index(index)

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/internals/construction.py:589[0m, in [0;36m_homogenize[0;34m(data, index, dtype)[0m
[1;32m    586[0m                 val [38;5;241m=[39m [38;5;28mdict[39m(val)
[1;32m    587[0m             val [38;5;241m=[39m lib[38;5;241m.[39mfast_multiget(val, oindex[38;5;241m.[39m_values, default[38;5;241m=[39mnp[38;5;241m.[39mnan)
[0;32m--> 589[0m         val [38;5;241m=[39m [43msanitize_array[49m[43m([49m
[1;32m    590[0m [43m            [49m[43mval[49m[43m,[49m[43m [49m[43mindex[49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m[43m [49m[43mraise_cast_failure[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m
[1;32m    591[0m [43m        [49m[43m)[49m
[1;32m    593[0m     homogenized[38;5;241m.[39mappend(val)
[1;32m    595[0m [38;5;28;01mreturn[39;00m homogenized

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/construction.py:576[0m, in [0;36msanitize_array[0;34m(data, index, dtype, copy, raise_cast_failure, allow_2d)[0m
[1;32m    573[0m             subarr [38;5;241m=[39m cast(np[38;5;241m.[39mndarray, subarr)
[1;32m    574[0m             subarr [38;5;241m=[39m maybe_infer_to_datetimelike(subarr)
[0;32m--> 576[0m subarr [38;5;241m=[39m [43m_sanitize_ndim[49m[43m([49m[43msubarr[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mdtype[49m[43m,[49m[43m [49m[43mindex[49m[43m,[49m[43m [49m[43mallow_2d[49m[38;5;241;43m=[39;49m[43mallow_2d[49m[43m)[49m
[1;32m    578[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(subarr, np[38;5;241m.[39mndarray):
[1;32m    579[0m     [38;5;66;03m# at this point we should have dtype be None or subarr.dtype == dtype[39;00m
[1;32m    580[0m     dtype [38;5;241m=[39m cast(np[38;5;241m.[39mdtype, dtype)

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/construction.py:627[0m, in [0;36m_sanitize_ndim[0;34m(result, data, dtype, index, allow_2d)[0m
[1;32m    625[0m     [38;5;28;01mif[39;00m allow_2d:
[1;32m    626[0m         [38;5;28;01mreturn[39;00m result
[0;32m--> 627[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mData must be 1-dimensional[39m[38;5;124m"[39m)
[1;32m    628[0m [38;5;28;01mif[39;00m is_object_dtype(dtype) [38;5;129;01mand[39;00m [38;5;28misinstance[39m(dtype, ExtensionDtype):
[1;32m    629[0m     [38;5;66;03m# i.e. PandasDtype("O")[39;00m
[1;32m    631[0m     result [38;5;241m=[39m com[38;5;241m.[39masarray_tuplesafe(data, dtype[38;5;241m=[39mnp[38;5;241m.[39mdtype([38;5;124m"[39m[38;5;124mobject[39m[38;5;124m"[39m))

[0;31mValueError[0m: Data must be 1-dimensional
ValueError: Data must be 1-dimensional

